Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)

# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**

In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr1 = np.array([1,2,3,4,5])
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr2 = np.array([[1,3,9],[1,9,81],[1,27,729]])
print(arr2)

[1 2 3 4 5]
[[  1   3   9]
 [  1   9  81]
 [  1  27 729]]

In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
random_array = np.random.rand(3,4)
print(random_array)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr3 = np.zeros((3,4))
print(arr3)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr4 = np.ones((3,4))
print(arr4)

[[0.98640193 0.98901861 0.59742976 0.92590673]
 [0.44605923 0.88598706 0.82151905 0.27304802]
 [0.50126395 0.9567719  0.44158901 0.43335447]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

import numpy as np
def evenly_spaced_interval(initial, final, interval):
    return np.arange(initial, final, interval)
initial = 5
final = 55
interval = 5

arr5 = evenly_spaced_interval(initial, final, interval)
print(arr5)

[ 5 10 15 20 25 30 35 40 45 50]

### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
arr_sum = np.add(a,b)
arr_diff = np.subtract(a,b)
arr_product = np.multiply(a,b)
arr_divide = np.divide(a,b)

print(arr_sum)
print(arr_diff)
print(arr_product)
print(arr_divide)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

def sum_along_axis_0(arr6):
    return arr6
arr6 = np.sum(a, axis=0)
print(arr6)

# Write a NumPy function to get the sum of the array 'a' along axis=1 

def sum_along_axis_1(arr7):
    return arr7
arr7 = np.sum(a, axis=1)
print(arr7)

[ 6 17 14]
[10 13 14]

In [ ]:
# Write a NumPy function to reverse the array 'a' 
def reversing_array_a(reversed_a):
    return reversed_a
reversed_a = np.flip(a)
print(reversed_a)


# Write a NumPy function to reverse the array 'a' along axis=0
def reversing_along_axis_0(arr8):
    return arr8
arr8 = np.flip(a, axis=0)
print(arr8)


# Write a NumPy function to reverse the array 'a' along axis=1
def reversing_along_axis_1(arr9):
    return arr9
arr9 = np.flip(a, axis=1)
print(arr9)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 

def sorting_a(sorted_a):
    return sorted_a
sorted_a = np.sort(a)
print(sorted_a)

# Write a NumPy function to sort the array 'a' along axis=0

def sorting_a_along_axis_0(arr10):
    return arr10
arr10 = np.sort(a, axis=0)
print(arr10)


# Write a NumPy function to sort the array 'a' along axis=1

def sorting_a_along_axis_1(arr11):
    return arr11
arr11 = np.sort(a, axis=1)
print(arr11)

# Write a NumPy function to sort the array 'a' in descending order along axis=0

def sorting_in_descending_order(sorted_a):
    return sorted_a
sorted_a = np.sort(a, axis=0)
arr12 = np.flip(sorted_a, axis=0)
print(arr12)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]

In [ ]:
# Write a NumPy function to argsort the array along axis=0
def argsort_along_axis_0(arr13):
    return arr13
arr13 = np.argsort(a, axis=0)
print(arr13)


# Write a NumPy function to argsort the array along axis=1
def argsort_along_axis_1(arr14):
    return arr14
arr14 = np.argsort(a, axis=1)
print(arr14)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arrays(a,b):
  c = np.concatenate((a,b))
  return c
c = concatenate_arrays(a,b)
print(c)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenating_along_axis_0(a,b):
    return d
d = np.concatenate((a,b), axis=0)
print(d)

# Note: You can do the same function using stacking, discover and try that :)
def concatenating_using_stack_function(a,b):
    return e
e = np.vstack((a,b))
print(e)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
num_dims = a.ndim
print(num_dims)

# Write a NumPy function to get the Shape of the array  
shape_array = a.shape
print(shape_array)


# Write a NumPy function to get the Size of the array
size_array = a.size
print(size_array)

2
(3, 3)
9

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshaped_a = np.reshape(a, (1,9))
print(reshaped_a)

[[4 6 8 9 3 1 1 8 5]]

In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 

# Note : Show atleast two different ways of doing this 

import numpy as np

def adding_new_axis_first(a):
    x = a[np.newaxis, :]
    return x
Method_1 = adding_new_axis_first(a)
print("Method 1:\n", Method_1)

def adding_new_axis_second(a):
    y = np.expand_dims(a, axis=0)
    return y
Method_2 = adding_new_axis_second(a)
print("Method 2:\n", Method_2)

Method 1:
 [[[4 6 8]
  [9 3 1]
  [1 8 5]]]
Method 2:
 [[[4 6 8]
  [9 3 1]
  [1 8 5]]]

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


element = a[0]
print("0 Index elements:", element)

arr_ = a[0,2]
print("Element at index (0,2):",arr_)

sliced_array = a[1:3, 0:2]
print("Sliced_array:\n", sliced_array)

0 Index elements: [4 6 0]
Element at index (0,2): 0
Sliced_array:
 [[0 3]
 [1 8]]

In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 

def values_greater_than_any_given_value(a, any_value):
    x = a > any_value
    satisfying_values = a[x]
    return satisfying_values
Required_values = values_greater_than_any_given_value(a,5)
print(Required_values)    

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

def values_satisfying_given_conditions(a):
    x = a > 3
    y = a % 2 == 0
    z = np.logical_and(x,y)

    satisfying_values = a[z]
    return satisfying_values

Required_values = values_satisfying_given_conditions(a)   
print(Required_values)

[6 8]
[4 6 8]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
copy_a = np.copy(a)
copy_a += 1
print(copy_a)

[[5 7 1]
 [1 4 2]
 [2 9 6]]

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.

#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd

def drop_missing_rows(df):
    df_dropped = df.dropna()
    return df_dropped
df = pd.DataFrame(iris_2d)
df_dropped = drop_missing_rows(df)
print(df_dropped)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.

def establishing_correlation(df):
    x = df.iloc[:, 0:2]
    correlation = x.corr()
    return correlation
    df = pd.DataFrame(iris_2d)
correlation = establishing_correlation(df)
print(correlation)

          0         1
0  1.000000 -0.109369
1 -0.109369  1.000000

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import pandas as pd

def calculate_stats(df,column):
    mean = df[column].mean()
    median = df[column].median()
    std_dev = df[column].std()
    return mean,median,std_dev
df = pd.DataFrame(iris_2d)
mean,median,std_dev= calculate_stats(df, 3)

print("Mean:",mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 1.1986666666666668
Median: 1.3
Standard Deviation: 0.7631607417008411

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import pandas as pd

def calculate_stats(df,column):
    mean = df[column].mean()
    median = df[column].median()
    std_dev = df[column].std()
    return mean,median,std_dev

df = pd.DataFrame(iris_2d)
mean,median,std_dev= calculate_stats(df, 3)

print("Mean:",mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 1.1986666666666668
Median: 1.3
Standard Deviation: 0.7631607417008411

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np
x = np.arange(4,dtype=np.int64)
y = np.ones_like(x)
print(y)

[1 1 1 1]

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1,10)
y = np.split(x,[4,6])
print(y)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np
arr = np.random.randint(0, 10, size=(2,5))
print("The Array:\n")
print(arr)

maximum_value = np.max(arr, axis=1)
minimum_value = np.min(arr, axis=1)
maximum_indices = np.argmax(arr, axis=1)
minimum_indices = np.argmin(arr, axis=1)

print("Maximun values of arr along second axis:", maximum_value)
print("Indices of maximun values along second axis:", maximum_indices)
print("Minimum values of arr along second axis:", minimum_value)
print("Indices of minimum values along second axis:", minimum_indices)

The Array:

[[6 2 5 8 8]
 [1 0 8 5 8]]
Maximun values of arr along second axis: [8 8]
Indices of maximun values along second axis: [3 2]
Minimum values of arr along second axis: [2 0]
Indices of minimum values along second axis: [1 1]

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd
import numpy as np

def count_num_unique_species(data):
   unique_species = data.nunique()
   return unique_species
data = pd.DataFrame(iris)
x = count_num_unique_species(data)
print("No. of unique species:",x)

No. of unique species: 0    35
1    23
2    43
3    22
4     3
dtype: int64

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import pandas as pd
import numpy as np

def bin_petal_length(data):
    data['petal_length_bin'] = pd.cut(data['petallength'], bins=[0, 3, 5, float('inf')], labels=['small', 'medium', 'large'], right=False)
    return data


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

iris_2d_binned = bin_petal_length(iris_2d)

print(iris_2d_binned)

     sepallength  sepalwidth  petallength  petalwidth         species  \
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

    petal_length_bin
0              small
1              small
2              small
3              small
4              small
..               ...
145            large
146            large
147            large
148            large
149            large

[150 rows x 6 columns]

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import pandas as pd

def frequent_petal_length(url):
    iris = pd.read_csv(url, header=None, names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'))
    most_frequent_value = iris['petallength'].mode().values[0]
    return most_frequent_value
    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

most_frequent_value = frequent_petal_length(url)

print("Most frequent value of petal length:", most_frequent_value)

Most frequent value of petal length: 1.5